import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
     title: "Ecommerce Website",
     description: "Generated by create next app",
}

import AuthProvider from "@/provider/AuthProvider"
import "react-toastify/dist/ReactToastify.css"
export default function RootLayout({
     children,
}: {
     children: React.ReactNode
}) {
     return (
          <html lang="en" suppressHydrationWarning>
               <body
                    className={inter.className}
                    suppressHydrationWarning={true}
               >
                    <AuthProvider>{children}</AuthProvider>
               </body>
          </html>
     )
}
