import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import { SpeedInsights } from "@vercel/speed-insights/next"
const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    adjustFontFallback: false,
    preload: true,
})

import Navbar from "@/component/Navbar/Nav"
import FooterPage from "@/component/FooterPage/FooterPage"
import AuthProvider from "@/provider/AuthProvider"
export const metadata: Metadata = {
    title: "Ecommerce Website",
    description: "Generated by create next app",
}
export const dynamic = "force-dynamic"
import "react-toastify/dist/ReactToastify.css"
import { ToastContainer } from "react-toastify"
import AI from "@/component/AI/AI"
import ChatWithAdmin from "@/component/ChatWithAdmin/ChatWithAdmin"
import { headers } from "next/headers"
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const headersList = headers()
    const header_url = headersList.get("x-url")

    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${inter.className} flex flex-col min-h-screen`}
                suppressHydrationWarning={true}
            >
                <AuthProvider>
                    <ToastContainer />
                    <Navbar />
                    <div className="pt-[90px] grow">{children}</div>
                    {header_url === "http://localhost:3000/chat" ? (
                        ""
                    ) : (
                        <>
                            <AI />
                            <ChatWithAdmin />
                        </>
                    )}

                    <FooterPage />
                </AuthProvider>

                <SpeedInsights />
            </body>
        </html>
    )
}
